services:
  - type: web
    name: ghost-ban
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: ACCESS_KEY
        value: GHOST-BAN-2026
    plan: free
