services:
  - type: web
    name: ghost-ban
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: ACCESS_KEY
        generateValue: true
      - key: NODE_VERSION
        value: 20